---
collections:
  - name: ibm.mas_devops
    version: ">=37.12.0,<38.0.0"
  - name: kubernetes.core
    version: ">=5.1.0,<7.0.0"
  - name: amazon.aws
    version: ">=11.1.0,<12.0.0"
  - name: community.general
    version: ">=10.3.0,<14.0.0"
  - name: ansible.utils
    version: ">=5.1.2,<7.0.0"
  - name: community.crypto
    version: ">=2.18.0,<4.0.0"
