site:
  title: MAS World 2026
  start_page: modules::index.adoc

content:
  sources:
    - url: ./
      start_path: showroom/content

asciidoc:
  attributes:
    ocp_version: "4.21"
    mas_version: "9.1"
    manage_version: "9.1"
    lab_title: "MAS World 2026"
    lab_duration: "2 hours"

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
