site:
  title: MAS World 2026
  start_page: mas-world-2026::index.adoc

content:
  sources:
    - url: ./
      start_path: showroom/content

asciidoc:
  attributes:
    ocp_version: "4.21"
    mas_version: "9.1"
    manage_version: "9.1"
    lab_title: "MAS World 2026"
    lab_duration: "2 hours"

ui:
  bundle:
    url: https://github.com/rhpds/showroom-ui/releases/download/v0.3.0/ui-bundle.zip
    snapshot: true
