site:
  title: Maximo World 2026
  start_page: modules::index.adoc

content:
  sources:
    - url: ./
      start_path: showroom/content
      edit_url: false

asciidoc:
  attributes:
    ocp_version: "4.21"
    mas_version: "9.2"
    manage_version: "9.2"
    lab_title: "Maximo World 2026"
    lab_duration: "2 hours"
    openshift_console_url@: "https://console-openshift-console.apps.example.com"
    openshift_cluster_ingress_domain@: "apps.example.com"
    openshift_api_url@: "https://api.example.com:443"
    mas_url@: "https://admin.mas.apps.example.com"
    mas_navigator_url@: "https://masworld.home.mas.apps.example.com"
    manage_url@: "https://manage.mas.apps.example.com"
    lab_username@: "userXX"
    lab_password@: "CHANGE_ME"  # pragma: allowlist secret
    seat_number@: "00"
    student_username@: "userXX"
    s3_bucket_name@: "CHANGE_ME"
    s3_access_key_id@: "CHANGE_ME"
    s3_secret_access_key@: "CHANGE_ME"  # pragma: allowlist secret
    s3_region@: "us-east-2"
    mas_admin_username@: "admin"
    mas_admin_password@: "CHANGE_ME"  # pragma: allowlist secret

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: partials/header-content.hbs
      contents: |
        <header class="header">
          <nav class="navbar">
            <div class="navbar-brand">
              <a class="navbar-item" href="{{{or site.url siteRootPath}}}">{{site.title}}</a>
              {{#if env.SITE_SEARCH_PROVIDER}}
              <div class="navbar-item search hide-for-print">
                <div id="search-field" class="field">
                  <input id="search-input" type="text" placeholder="Search the docs"{{#if page.home}} autofocus{{/if}}>
                </div>
              </div>
              {{/if}}
              <button class="navbar-burger" aria-controls="topbar-nav" aria-expanded="false" aria-label="Toggle main menu">
                <span></span>
                <span></span>
                <span></span>
              </button>
            </div>
            <div id="topbar-nav" class="navbar-menu">
            </div>
          </nav>
        </header>
    - path: partials/edit-this-page.hbs
      contents: ''
