---
fleet:
  attendee_cluster_count: 1
  spare_cluster_count: 0
  facilitator_cluster_count: 1
  require_exact_cluster_counts: false
  preparation:
    max_concurrent_clusters: 1

student_credentials:
  allow_shared_password: true

secrets:
  provider: env

logging_config:
  log_level: debug
