site:
  title: MAS World 2026
  start_page: mas-world-2026::index.adoc

content:
  sources:
    - url: ./
      start_path: content

asciidoc:
  attributes:
    ocp_version: "4.21"
    mas_version: "9.1"
    manage_version: "9.1"
    lab_title: "MAS World 2026"
    lab_duration: "2 hours"
    user: "{user}"
    password: "{password}"
    openshift_console_url: "{openshift_console_url}"
    openshift_cluster_ingress_domain: "{openshift_cluster_ingress_domain}"
    mas_url: "{mas_url}"
    showroom_url: "{showroom_url}"
    guid: "{guid}"
    seat_number: "{seat_number}"

ui:
  bundle:
    url: https://github.com/rhpds/showroom-ui/releases/download/v0.3.0/ui-bundle.zip
    snapshot: true
