---
title: MAS World 2026
theme: rhpds-summit
tabs:
  - title: OpenShift Console
    url: https://console-openshift-console.${DOMAIN}
    position: right
    type: console

  - title: Maximo
    url: https://admin.inst1.${DOMAIN}
    position: right
    type: iframe

  - title: Grafana
    url: https://grafana-openshift-logging.${DOMAIN}
    position: right
    type: iframe
